name: bench

on:
  push:
    branches: ["master", "ci"]
  pull_request: 
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 3
        submodules: "recursive"
    - name: Cache Dependency
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          /usr/local/riscv64-unknown-elf/
          /usr/local/bin/riscv64-unknown-elf*
          /usr/local/share/verilator
          /usr/local/bin/verilator*
        key: ${{ runner.os }}-${{ hashFiles('scripts/intall_depend.sh') }}
        restore-keys: ${{ runner.os }}-${{ hashFiles('scripts/intall_depend.sh') }}
        
    - name: Install Dependency
      run: |
        cd scripts
        ./install_depend.sh --all
        cd ../utils/NEMU  
        export NEMU_HOME=/home/runner/work/DOoO-riscv/DOoO-riscv/utils/NEMU
        make defconfig
        make riscv64-do-ref_defconfig CPT_CROSS_COMPILE=riscv64-unknown-elf-
        cd ../riscv-tests/isa
        make XLEN=32 -j8
        cd ../benchmarks
        make XLEN=32 -j8

    - name: Run Tests
      run: |
        scripts/isa_test.sh all
