name: bench

on:
  push:
    branches: ["master", "ci"]
  pull_request: 
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 3
        submodules: "recursive"
    - name: Install Dependency
      run: |
        cd scripts
        ./install_depend.sh all
    
    - name: Run Tests
      run: |
        scripts/isa_test.sh all
